apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
data:
  # These are base64 encoded values
  MONGO_ROOT_USERNAME: c2hva2lyYWoyNDEy     # 'admin' in base64
  MONGO_ROOT_PASSWORD: oFIiXpbQLRh5Jje6  # 'password' in base64 